### PR TITLE
fix(SearchParameters)Supports for unknown parameters

### LINKED ISSUE #200: Throw on unsupported parameter
We have been getting issues on new parameters being used and not yet available on the helper.

Right now we were silently failing making it hard to understand what's going on, following #198 we should throw in V3. Why V3? Because this could now possibly break a good number of implementations and websites.

BTW @bobylito can you re explain why do we need to declare all of the parameters explicitly instead of doing `forEach(params, param => this.paramName = this.paramValue)`?

### PR DESCRIPTION
**Pull request by bobylito**
Will warn once on unknown parameters.
Fixes #200 but instead of throwing, it will accept all parameters, just warn.

### CODE REVIEW

File: src/functions/warnOnce.js [hunk 1]
```diff
@@ -0,0 +1,19 @@
+'use strict';
+
+var bind = require('lodash/function/bind');
+
+var warn = window ?
+  window.console && bind(window.console.warn, console) :
+  bind(console.warn, console); // eslint-disable-line no-console
+
+var warnOnce = (function(w) {
+  var previousMessages = [];
```
Comment (vvo) [inline src/functions/warnOnce.js]: The array will only grow by the number of different parameters we use right?

**Comment by vvo** [comment]
LGTM

File: src/functions/warnOnce.js (hunk 1 above)
Comment (bobylito) [inline src/functions/warnOnce.js]: Yes, it will grow by one for each new message generated. Do you think it might a problem? Maybe we should deactivate that in the minified version?

Comment (vvo) [inline src/functions/warnOnce.js]: Should be ok since it only grows on the number of "unknown" params, not by the number of calls to setQueryParameter etc..

**Comment by bobylito** [comment]
The war (with the tests) is over :) Merging!
