### PR TITLE
fix: isDisjunctiveRefined() and isRefined() return true/false

### LINKED ISSUE #123: helper.isDisjunctiveRefined() returns true or undefined
Using `helper.isDisjunctiveRefined(name, value)` when the value is not refined, I get `undefined`.

I would expect to get either `true` or `false`.

Is this expected behavior?

If not, I will PR :-)

### PR DESCRIPTION
**Pull request by vvo**
instead of true/undefined
fixes #123

### CODE REVIEW

File: src/SearchParameters/RefinementList.js [hunk 1]
```diff
@@ -129,13 +129,16 @@ var lib = {
       refinementList[attribute].length > 0;
 
     if (isUndefined(refinementValue)) {
-      return containsRefinements;
+      return containsRefinements ? true : false;
```
Comment (bobylito) [inline src/SearchParameters/RefinementList.js]: Is this way of converting to boolean idiomatic?

I would go for the `!!var`.

Comment (vvo) [inline src/SearchParameters/RefinementList.js]: Added the !!

**Comment by bobylito** [comment]
:+1: ;)
