### PR TITLE
fix(numerics) : removeNumericFilters(attribute) was not working FIX #230

### LINKED ISSUE #230: removeNumericRefinement(attribute)
Hi there,

[According to the README.md](https://github.com/algolia/algoliasearch-helper-js/blob/master/README.md#batch-numeric-filter-removal) we should be able to do `removeNumericRefinement(attribute)`

But if you look at the code, it looks like you need to specify at least the couple `(attribute, operator)`: https://github.com/algolia/algoliasearch-helper-js/blob/43bae7b06366effa13328500bf4bb59682157316/src/SearchParameters/index.js#L700-L732

Did you remove this functionality?

### PR DESCRIPTION
**Pull request by bobylito**

### CODE REVIEW

**Comment by bobylito** [comment]
Anyone up for a review @redox @pixelastic @pixelastic @proudlygeek ?

File: src/SearchParameters/index.js [hunk 1]
```diff
@@ -705,16 +705,16 @@ SearchParameters.prototype = {
...
     if (paramValue !== undefined) {
+      if (!this.isNumericRefined(attribute, operator, paramValue)) return this;
       return this.setQueryParameters({
         page: 0,
         numericRefinements: this._clearNumericRefinements(function(value, key) {
           return key === attribute && value.op === operator && value.val === paramValue;
         })
       });
-    } else if (operator) {
+    } else if (operator !== undefined) {
```
Comment (proudlygeek) [inline src/SearchParameters/index.js]: This way you lose checks against ```null```and ```false```. Is what you want?

p.s. Even if it's slower I usually use ```typeof operator === 'undefined'```, which has the advantage of working also when the variable is not defined.

Comment (bobylito) [inline src/SearchParameters/index.js]: Yes you're right! And I do want to check the number of parameters, I do not care much about their type. It's also done for consistency with existing test, a few lines above.

**Comment by proudlygeek** [comment]
LGTM :+1:

**Comment by bobylito** [comment]
Cool thanks for the review @proudlygeek :)

File: src/SearchParameters/index.js (hunk 1 above)
Comment (pixelastic) [inline src/SearchParameters/index.js]: You might even remove the `else` here, because you always `return` in the previous `if`

File: src/SearchParameters/index.js [hunk 2]
```diff
@@ -1139,12 +1140,15 @@ SearchParameters.prototype = {
...
-   * @param {string} operator operator of the refinement
+   * @param {string} [operator] operator of the refinement
    * @param {string} [value] value of the refinement
    * @return {boolean} true if it is refined
    */
   isNumericRefined: function isNumericRefined(attribute, operator, value) {
     if (isUndefined(value)) {
+      return !!this.numericRefinements[attribute];
+    }
+    if (isUndefined(value)) {
```
Comment (pixelastic) [inline src/SearchParameters/index.js]: Hmm, this check will never pass, because you already checked for that and returned above

Comment (bobylito) [inline src/SearchParameters/index.js]: that's a bummer :/

File: test/spec/helper.numericFilters.js [hunk 3]
```diff
@@ -80,6 +80,52 @@ test('Should be able to remove values one by one even 0s', function(t) {
...
+
+  t.deepEqual(
+    helper.getRefinements('attribute'),
+    [{type: 'numeric', operator: '<', value: [4]}],
+    'should have the same result with getRefinements');
+
+  t.end();
+});
+
+test('Should remove all the numeric values for a single operator if remove is called with two arguments', function(t) {
```
Comment (pixelastic) [inline test/spec/helper.numericFilters.js]: Bad copy paste :)

File: test/spec/helper.numericFilters.js [hunk 4]
```diff
@@ -80,6 +80,52 @@ test('Should be able to remove values one by one even 0s', function(t) {
...
+
+  t.deepEqual(
+    helper.getRefinements('attribute'),
+    [],
+    'should have the same result with getRefinements');
+
+  t.end();
+});
+
 test('should be able to retrieve numeric filters', function(t) {
```
Comment (pixelastic) [inline test/spec/helper.numericFilters.js]: Empty test?

File: src/SearchParameters/index.js (hunk 1 above)
Comment (bobylito) [inline src/SearchParameters/index.js]: I don't agree on the remove everything that is not mandatory policy ;)

File: test/spec/helper.numericFilters.js (hunk 3 above)
Comment (bobylito) [inline test/spec/helper.numericFilters.js]: Indeed :/

File: src/SearchParameters/index.js (hunk 1 above)
Comment (pixelastic) [inline src/SearchParameters/index.js]: It just adds more branches (`if`, `else`, etc) which makes code harder to read. The less code you write, the less bug you have :)

Comment (bobylito) [inline src/SearchParameters/index.js]: I do not agree, it expresses the completness of the tests without having to read inside :)

Comment (pixelastic) [inline src/SearchParameters/index.js]: Yep, makes sense. More of personal preference, without much incidence I guess.

Comment (bobylito) [inline src/SearchParameters/index.js]: That is something we agree on :D
